// Generated by CoffeeScript 1.3.3
(function() {
  var bindKeyColor, clearColor, paint, setKeyAction, setPallete;

  paint = 'purple';

  setKeyAction = function() {
    $(document).keydown(function(e) {
      return $("#k" + e.keyCode).addClass('active');
    });
    return $(document).keyup(function(e) {
      return $("#k" + e.keyCode).removeClass('active');
    });
  };

  setPallete = function() {
    $('.circle').each(function() {
      $(this).css('background', $(this).data('code'));
      return $(this).click(function() {
        paint = $(this).data('color');
        $("#pallete .active").removeClass('active');
        $(this).addClass('active');
        $("#indicator").css('left', $(this).position().left);
        return $("#indicator").css('color', $(this).data('code'));
      });
    });
    return $('#indicator').click(function() {
      return $('.key').click();
    });
  };

  clearColor = function(ele) {
    ele.removeClass('color-black');
    ele.removeClass('color-white');
    ele.removeClass('color-beige');
    ele.removeClass('color-gray');
    ele.removeClass('color-red');
    ele.removeClass('color-blue');
    ele.removeClass('color-green');
    ele.removeClass('color-yellow');
    ele.removeClass('color-orange');
    ele.removeClass('color-pink');
    return ele.removeClass('color-purple');
  };

  bindKeyColor = function() {
    return $('.key').each(function() {
      return $(this).click(function() {
        clearColor($(this));
        return $(this).addClass("color-" + paint);
      });
    });
  };

  $(function() {
    setKeyAction();
    setPallete();
    bindKeyColor();
    return $('#pallete .circle').first().click();
  });

}).call(this);
