// Generated by CoffeeScript 1.3.3
(function() {
  var setKeyAction, setKeyColor;

  setKeyAction = function() {
    $(document).keydown(function(e) {
      return $("#k" + e.keyCode).addClass('active');
    });
    return $(document).keyup(function(e) {
      return $("#k" + e.keyCode).removeClass('active');
    });
  };

  setKeyColor = function() {
    return $('.key').each(function() {
      return $(this).addClass("color-" + ($(this).data('color')));
    });
  };

  $(function() {
    setKeyAction();
    return setKeyColor();
  });

}).call(this);
